quick_build = yes
release_dir = release
tweak_google = no
check_lephone = yes
umeng_channels = update_64
v2_sign_channels = update_64
v2_sign_enable = true
flavor = hongguo
enable_res_guard = yes
enable_debug_build = no
